# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b053494af404e60eb17e721b58c374fe9f01f7a4eb849295bcc07940dc614108f91ffeddf550031e7a6b0283018d759fcca1ef39a9883a8c06ce35e73e40e45

test:
  secret_key_base: c72b272025075265bc6de825bc73082728d057ce25444f745d827e874dbdf3f46eb44e91b451ba3d3cfff40cfbd1e35fa29aae1f9da7cec15753bc15c165f7d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
